### ISSUE TITLE
可以修改为扫码获取抖音cookie吗，搞了一天了还是没有成功

### ISSUE THREAD

**Issue by Haoqi7** [lemon8866/spirit#12]
可以修改为扫码获取抖音cookie吗，搞了一天了还是没有成功，使用https://github.com/Johnserf-Seed/TikTokDownload获取的cookie复制进去也无法使用

**Comment by lemon8866** [comment]
抖音扫码功能正在准备接入 如果使用Johnserf-Seed/TikTokDownload获取的cookie不能用 需要排除是否因为其他问题  。可以提供一下使用的下载器类型和提交抖音链接后docker的容器日志

**Comment by lemon8866** [comment]
归入年后更新计划版本
