### ISSUE TITLE
推送失败问题

### ISSUE THREAD

**Issue by Tyc-github** [lemon8866/spirit#13]
安卓和win端的客户端都试过了，都是推送不了，手机是一直转圈，电脑是客户端推送了没反应。B站的收藏夹下载功能也是只能识别出来有多少个视频，但就是不推送给aria2。感觉可能是aria2的配置问题，但他能正常下载东西，spirit的设置反复对比了好像没有哪里输错了
<img width="506" alt="微信图片_20231216014640" src="https://github.com/lemon8866/spirit/assets/67275209/03037972-2a19-46cf-ab2c-2e5d82f9f992">

**Comment by lemon8866** [comment]
手机小程序推送失败的话需要开启调试模式   如果是APP的话 可以先确认一下接口是否能正常访问   
http://ip:port/api/processingVideos
之前别人测试的时候aria的下载目录只能是/downloads    不知道你是不是这个情况  可以先尝试选用http下载   http下载直接选择 就可以 其他信息都不需要填写
