### ISSUE TITLE
请问YouTube的视频怎么设置？

### ISSUE THREAD

**Issue by ChanLicher** [lemon8866/spirit#14]
看到界面说是支持YouTube，但是收藏下载里面没法设置监控YouTube账号

**Comment by lemon8866** [comment]
目前停更状态  
youtube 暂时只是支持推送下载
收藏下载目前仅支持 抖音 哔哩哔哩  
其他平台收藏监控 划入下一版本迭代 
预计年后恢复更新 在完成其他计划未完成的功能
