### ISSUE TITLE
bili_ticket 参数的用途是什么呢

### ISSUE THREAD

**Issue by cctyl** [lemon8866/spirit#9]
作者你好，我也在调用bili api，但是有个 bili_ticket 参数不太懂，这个参数有什么用呢

**Comment by Confession1995** [comment]
具体有什么作用不太清楚,只知道这个是jwt 生成的令牌
可以使用解密工具解密看一下https://www.box3.cn/tools/jwt.html
可能是代表session token 的签发时间之类的
